version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: mylibraby
      POSTGRES_PASSWORD: mylibrary
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
